fixtures:
  repositories:
    stdlib:  https://github.com/puppetlabs/puppetlabs-stdlib.git
    registry: https://github.com/puppetlabs/puppetlabs-registry.git
    powershell:  https://github.com/puppetlabs/puppetlabs-powershell.git
  symlinks:
    windows_firewall: "#{source_dir}"
